### ISSUE TITLE
"failed to load: Experimental keys on scalar is now forbidden ..." (again)

### ISSUE THREAD

**Issue by pms967** [marcoc1712/C-3PO#10]
Dopo aver visto il msg nell'altro issue, ho provato a caricare la nuova beta (v2.01.02). Ma mi sa che qualcosa che avevi sistemato nella stabile non è passato: ci risiamo...
```
[17-04-06 00:35:52.8740] Slim::Utils::PluginManager::load (241) Loading plugin: C3PO
[17-04-06 00:35:52.8790] Slim::Utils::Misc::msg (1244) Warning: [00:35:52.8788] Subroutine preferences redefined at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/C3PO/PreferencesHelper.pm line 53.
[17-04-06 00:35:52.9653] Slim::bootstrap::tryModuleLoad (286) Warning: Module [Plugins::C3PO::Plugin] failed to load:
Experimental keys on scalar is now forbidden at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/C3PO/Plugin.pm line 622.
Compilation failed in require at (eval 925) line 1.
BEGIN failed--compilation aborted at (eval 925) line 1.
```

**Comment by marcoc1712** [comment]
sono due nuove righe... 
il fatto che non segnali nemmeno una warning con use strict e use warnings attivo è micidiale, l'abitudine porta a dimenticarsene...

Rilascio la nuova versione.

**Comment by marcoc1712** [comment]
ma su che sistema stai usando quella versione PERLmalosa?

**Comment by pms967** [comment]
> ma su che sistema stai usando quella versione 

Debian 9 ("Stretch"). Anche se ancora non è stata rilasciata ufficialmente come nuova "stable", ormai è "frozen" (solo rifiniture e bug fix) già da un po' e sono passato a quella.

> PERLmalosa?

LOL! :D :D

**Comment by pms967** [comment]
OK, funziona! Belle le novità. 

BTW: non disponibile si scrive "unavailable", con una 'L' sola... ;-) 

P.S.: non che mi interessi, ma come mai aac risulta indisponibile? Il codec ce l'ho... (e IIRC lo gestisce anche ffmpeg).

**Comment by marcoc1712** [comment]
aac è 2 cose: apple lossles che c'è e aac = mp3 x apple, che in quanto
lossy non c'è. Putroppo con i nomi dei codecs e formati tra squeezelite,
lms e sox è un turbinio...

Grazie per la segnalazione del maccheronico, segnale ogni volta che le
trovi.

Il giorno 6 aprile 2017 22:08, pms967 <notifications@github.com> ha scritto:

**Comment by marcoc1712** [comment]
chiudo
