### ISSUE TITLE
Feature request: add missing sdm options

### ISSUE THREAD

**Issue by pms967** [marcoc1712/C-3PO#11]
Ciao Marco,

you've recently asked about any feature still missing. I answered "basically none" but, well... I did forgot about the "extra" options (-t,-n,-l) of the sdm function:

https://www.nexthardware.com/forum/pc-top-software/89323-dsd-lms-con-sox-98.html#post975953
```
sdm [-f filter] [-t order] [-n num] [-l latency]

       Apply  a  1-bit  sigma-delta  modulator  producing DSD output.  The input 
       should be previously upsampled, e.g. with the rate effect, to a high rate, 
       2.8224MHz for DSD64.  The -f option selects the noise-shaping filter from 
       the following list where the number indicates the order of the filter:

                 clans-4      sdm-4
                 clans-5      sdm-5
                 clans-6      sdm-6
                 clans-7      sdm-7
                 clans-8      sdm-8

       The noise filter may be combined with a partial trellis/viterbi search 
       by supplying the following options:

       -t     Trellis order, max 32.

       -n     Number of paths to consider, max 32.

       -l     Output latency, max 2048.

       The result of using these parameters is hard to predict and can include
       high noise levels or instability. Caution is advised.
```
As warned in the man page, those options can be potentially "dangerous"... but they can also have a significant impact on the perceived sound quality. Hence they are rather important for our goals. 

Though labeled as "advanced" and with clear warning about the possible problems they can cause (as well as something like "_do not change, use defaults unless you know what you are doing_" and "_keep volume very low while testing_"), IMHO they should be added. 

I would add them in the form of drop-down menus or sliders to set the corresponding parameter.

For each of them there must be the possibility (enabled by default) to **_not_** include the corresponding option in the generated sox command line. Perhaps a "use default" check-box next to the slider, or the same label included as the first (and default) entry in the menu.

Maybe we should ask Mans for guidelines about how to reasonably set those params (if you do ask, please add me in CC:) and include them in the "info" shown next to them.

**Comment by marcoc1712** [comment]
Hii paolo, 

-f is already included, 

-t, -n. -l are new? starting from what version?  

Thanks.

**Comment by pms967** [comment]
> -t, -n. -l are new? 

no. The man page I quoted is from the same version we are using (masr's one, of course).

**Comment by marcoc1712** [comment]
SOX version >= 14.04.02 & dsF or dff supported. Same as sdm controll, then.
Correct?

**Comment by marcoc1712** [comment]
in 2.0.2.04
