### ISSUE TITLE
Ripristinare il Target sample rate (per default = al massimo) anche per DSD.

### ISSUE THREAD

**Issue by marcoc1712** [marcoc1712/C-3PO#13]
Da pm67:

In alcuni casi può avere senso: se ad es. avessi un DAC che supporta fino a 384K (o più) ma ha uno "sweet spot" (suona leggermente meglio) ad un certo s/r più basso, ad es. 96 o 192, probabilmente sarebbe vantaggioso ricampionare proprio a quella frequenza tutto il materiale con s/r inferiori. Però, se ho del materiale nativo a s/r più alto, è possibile per non dire probabile che non mi convenga "downsamplarlo": facile che quello che guadagnerei per via dello "sweet spot" del DAC lo perderei con gli interessi a causa del downsampling.

La cosa poi è particolarmente importante con il DSD. Prendi il mio caso (che non è poi così atipico): ho un DAC che supporta fino a DSD512 (teoricamente addirittura 1024), ma il PC che fa da server non è in grado di convertire da PCM (e tanto meno "upsamplare" DSD) oltre DSD128. Ora, di files DSD nativi a 512 ed oltre non ne ho mai visti (e considerati i pochissimi sistemi audio in grado di supportarli e le dimensioni folli, dubito ce ne siano...), ma DSD256 sì.

Va da sé che, in simili condizioni, idealmente ciò che vorrei ottenere è che (ad es.) PCM e DSD64 siano convertiti in DSD128 (di più non posso), mentre DSD128 e superiori siano inviati in uscita così come sono.

**Comment by marcoc1712** [comment]
forseho  finalmente capito a cosa servirebbe il 'target': 

a consentire di ricampionare ad una frequenza diversa dalla massima (o massima sincrona) ammessa, senza provocare il downsampling di quelle superiori ammesse, corretto?

Cioè impostando il target a 128, ove 256 è il massimo e 128 il minimo:

a. ricampiono 64 a 128, 
b. non tocco 128 e 256,
c. faccio downsample del 512. 

Corretto?

Per pcm, analogamente, potrei ricampionare tutto fino a 96K a 96K, non toccare 96 e 192, ma fare downsampling oltre.

Domanda:

perché solo una soglia?

La cosa non sarebbe meglio resa da una tabella simile a questa:

44.1 [ ] 96000
48 [ ] 96000
88.2 [ ] 96000
96 [x] _____
...
176.4 [] 384000
192 [] 384000
352.8 [] 384000
384 [x] _____
...
768 [] 384000

-----------------------------------------------------------------------------------------------------------------
p.s.

Sento già qualcuno opinare: perché uguale per tutti i formati di ingresso? 

quindi dovrei mettere una cosa di questo tipo:

[incodec] [inSR] out s/r

ma avrebbe molto senso poter differenziare tra file locali, remoti o stream, quindi:

{[F] [R] [I]} [incodec] [inSR] out s/r 

a quel punto, sarebbe comodo poter differenziare anche il formato di uscita

{[F] [R] [I]} [incodec] [inSR] outcodec out s/r 

Ci sono poi in C-3PO scelte arbitrarie sull'usare o meno certi strumenti come i cue sheets, flac o FFMPEG per separare i brani, FAAD o FMPEG per AIFF ed ALAC, FLAC/SOX per FLAC,... si potrebbero esporre le scelte così:

{[F] [R] [I/T]} [incodec] [outcodec] [inSR] out s/r [SPLITTER] [CONVERTER] [RESAMPLER]

che guarda caso è molto simile alla definizione di un comando di custom convert.conf. Era ESATTAMENTE la prima idea di C-3PO che mi ero fatto.

A tempo, voglia e capacità infinite potrei inventare un sistema di settaggi a più livelli (semplice, avanzato, esperto, guru) che via via espone diverse possibilità di scelta, ma bisogna anche fare i conti con lo strumento che si ha a disposizione, che non è certo nato per questo. La complessità (anche grafica) di C-3PO è già oggi molto superiore a quella di qualsiasi altro plugin di LMS.

Prendo nota della richiesta, ma a bassa priorità, magari nel contesto di una revisione completa della UI in futuro.

**Comment by pms967** [comment]
> forse ho finalmente capito a cosa servirebbe il 'target':
>
> a consentire di ricampionare ad una frequenza diversa dalla massima (o massima sincrona) ammessa, senza provocare il downsampling di quelle superiori ammesse, corretto?

esatto!

> Domanda:
> perché solo una soglia?
> La cosa non sarebbe meglio resa da una tabella [...]

A meno che non ci sia qualche caso a cui non ho pensato e che mi sfugge, non riesco a vederne l'utilità pratica. Perciò l'idea di creare una tabella tipo quella che suggerivi mi sembra solo inutilmente complessa. 
(soprattutto per quanto riguarda la gestione da parte dell'utente: così facendo finiresti col ricreare tutta la complessità ed "_incomprensibilità_" del "convert.conf"... e non mi pare proprio il caso. Uno dei vantaggi - IMHO tutt'altro che secondari - di C3PO sta proprio nella _semplificazione_ della gestione della configurazione, pur mantenendo le funzionalità che servono).

La "singola soglia" (il "target s/r") sarebbe utile (e più che sufficiente) nei casi pratici (e relativamente comuni) che citavo: per il PCM potrebbe essere ad es. il caso di chi (come te) ha DAC R2R NOS (che di solito vanno meglio con un po' di upsampling, ma vanno peggio con s/r "troppo alti"), mentre per il DSD è ad es. il caso di chi si trova in condizioni simili alle mie (DAC che supporta "di tutto", ma server con risorse limitate). 

Quale sarebbe invece l'utilità pratica di creare una "mappatura" completa di ogni possibile combinazione, addirittura distinta a seconda del formato?

Certo otterresti la max flessibilità e potresti fare tutto (o quasi) con quella tabella, eliminando i vari "max sync" / "max async", ecc, nonché, forse, anche la tabella dei s/r supportati. 

Però, (IMO) dal punto di vista dell'utente la configurazione risulterebbe meno intuitiva e molto più laboriosa, nonché molto più soggetta a possibili errori (intesi come combinazioni indesiderate, impostate per sbaglio o dimenticanza).

IMHO per l'utente è molto più semplice ed intuitivo dire: "in uscita voglio questo s/r, ma se è possibile non voglio che materiale con s/r maggiore sia downsamplato" piuttosto che dover dire: "se ho X voglio Y, se ho K voglio Z, ecc, ecc, ecc, per tutte le possibili combinazioni. 

Nel primo caso devo impostare soltanto due cose, assolutamente ovvie ed intuitive: 
1) ciò che supporta la mia interfaccia 
2) il s/r che voglio ottenere in uscita in caso di upsampling
per giunta è probabile che dopo la prima configurazione iniziale il punto 1) non lo tocco mai più e, per tutte le prove che potrei voler fare, mi trovo a dover cambiare una unica impostazione.

Al contrario nell'altro caso: tanto all'inizio quanto ogni volta che decido di provare a cambiare qualcosa sarei costretto a dover scorrere e cambiare una marea di settings (l'intera tabella, o quasi). Una seccatura enorme...

**Comment by marcoc1712** [comment]
Se risolvessi la cosa con una nuova (serie di ) opzione(i):  "alla più prossima ammessa"

abilitando 128 e 256 otterrei che 64 viene sovracampionata a 128 e 512 riportataa  256, ma sia 128 che 256 rimangono intoccate.

Analogamente per PCM e comprendendo sempre le opzioni massima assoluita, massima sincrona a massima irrazionale (anche se forse sarebbe più chiaro non sincrona).

MI pare che risolva,  senza dover inserire l'ulteriore parametro.

**Comment by marcoc1712** [comment]
Anzi, pensandoci meglio, potrei ridurre il tutto a

1. scelta dei sample rate ammessi in uscita, come è oggi.
2. prossimo 'sincrono', 'non sincrono' o 'qualsiasi'. (con fault back su "qualsiasi", in ogni caso).
3. eliminerei il 'quando', dato che:
a. La scelta 'mai' è ridondante rispetto alla tabella funzioni/formato.
b. 'sempre' corrisponde a selezionare solo 1 (o 2 per il sincronismo) sample rates.
c. 'solo quando non abilitato' Diventa la norma, tutto viene sempre ricampionato al più prossimo (sincrono o meno) sample rate abilitato nella tabella, TRANNE proprio le frequenze abilitate.

A me pare sia possibile tutto quanto ipotizzato fino ad ora e semplifichi le cose, attribuendo un significato univoco e più chiaro alla tabella dai sample rates: Sono quelli abilitati in uscita al transcoder, gli altri- per necessità - devono essere convertiti. e ricondotti a questi, secondo una regola di prossimità.

Che ne pensate?

**Comment by marcoc1712** [comment]
risolto in 2.2.3
