### ISSUE TITLE
PCM->DSD non funziona

### ISSUE THREAD

**Issue by pms967** [marcoc1712/C-3PO#2]
...a occhio e croce, non viene scritto il sample-rate nei comandi di sox:

 "flc-dsf-*-00:1c:c0:37:22:73" => {
                                     capabilities => { D => "RESAMPLE=-r %d", F => "noArgs", I => "noArgs", R => "noArgs" },
                                     command      => "[flac] -dcs --totally-silent \$START\$ \$END\$ -- \$FILE\$ | [sox] -q -t wav - -t dsf -b 1 -  gain -h rate -v -L -b 95  sdm -f sdm-8",
                                     profile      => "flc-dsf-*-00:1c:c0:37:22:73",
                                   },
  "wav-dsf-*-00:1c:c0:37:22:73" => {
                                     capabilities => {
                                                       D => "RESAMPLE=-r %d",
                                                       F => "noArgs",
                                                       R => "noArgs",
                                                       T => "START=-ss %s",
                                                       U => "END=-t %w",
                                                     },
                                     command      => "[ffmpeg] -vn -v 0 \$START\$ \$END\$ -i \$FILE\$ -f wav - | [sox] -q -t wav - -t dsf -b 1 -  gain -h rate -v -L -b 95  sdm -f sdm-8",
                                     profile      => "wav-dsf-*-00:1c:c0:37:22:73",
                                   },
}

**Comment by pms967** [comment]
P.S.: PCM->PCM invece funziona (ma non funziona se abilito i cue sheet su input flac).

**Comment by marcoc1712** [comment]
ci sto lavorando

**Comment by marcoc1712** [comment]
risolto, nel prossimo commit e rilascio.
