### ISSUE TITLE
Non si può abilitare PCM->DSD se DSD disabilitato in ingresso

### ISSUE THREAD

**Issue by pms967** [marcoc1712/C-3PO#3]
Non consente di abilitare l'uscita su DSD se tra i formati di ingresso DSF e DFF sono disabilitati.

**Comment by marcoc1712** [comment]
Non ècosì. 

Se DSF e/o DFF sono supportati (appaiono come selezionabili nei settngs generali) è possibile selezionare l'uscita - sempre nei parametri generali -  in dsd, anche se non li si abilita.

Solo se il player non supporta DSD allora non sarà possibile selezionarli come formati di uscita. per lo psecifico player.

Se non ti torna sia così, specifica per favore meglio i sintomi che rilevi.
