### ISSUE TITLE
request:  configuration interface changes

### ISSUE THREAD

**Issue by pms967** [marcoc1712/C-3PO#4]
Please remove everything but "Supported input formats" and "Default Enable C-3PO for new players" from the "GENERAL SETTINGS" tab.

Leave/move everything else (only) in "PLAYER SETTINGS".

(also remove the "Use global settings" and "Show details" buttons).

If possible, also include (within the player settings) a direct link to the "general settings". 

Tnx. :-)

**Comment by marcoc1712** [comment]
As already planned, is done in v. 2.00.08 (in beta repository now)
