### ISSUE TITLE
Richiesta features

### ISSUE THREAD

**Issue by simonefil** [marcoc1712/C-3PO#5]
Ciao Marco; ti suggerisco due features da aggiungere per la prossima release che a mio parere possono essere molto utili:

1- Menu "Ricampiona:"; insieme a "Sempre", "Mai", "Solo se la frequenza di campionamento non è supportata" aggiungere "Solo per file 16bit 44.1Khz". Fare upsampling a file già in Hi-Res a poco senso e a volte ho pure notato una degradazione sonora; mentre se si limitasse ai 16/44.1 sarebbe ottimo!

2- Aggiunta al menu Avanzate -> C-3PO (le impostazioni generale). Una casella con: "Enable SoX multi-thread". Ora come ora con una conversione PCM->DSD128 SoX si "beve" il 50% di un core fisico di uno Xeon X5570; che all'incirca è la potenza di un core di un i5 di penultima generazione o un core di un i3 ultima gen. In questo modo si escludono tutte le cpu che sono multi core con TDP molto basso (molte fanless) come i pentium 4core, gli atom 4core e 8core fanless (stile il c2750) che in multithreading riuscirebbero a convertire ma in single core non ce la fanno.

**Comment by marcoc1712** [comment]
1. si può fare, con alcune limitazioni in windows, purtroppo. 

2. Ma la cosa che dici si trasforma in un parametro di lancio di sox? Se si, si può fare (...se mi dici il parametro da usare, come selezionarlo, eventuali dipendenze da altri parametri,....) 

Marco la cosa come richiesta di migliria e la lascio open.

p.s.

Meglio mettere una richiesta per volta.

**Comment by simonefil** [comment]
1- Sarebbe comunque un'ottima feature!
2- Sì, è un parametro di lancio di sox; basta che tu aggiunga alla stringa −−multi−threaded; è consigliabile anche aumentare il buffer (di default 8192 [byte]) per una questione di prestazioni con l'opzione --buffer 131072 ->(cifra consigliata nella documentazione nel caso si utilizzi il multi thread)

**Comment by pms967** [comment]
Sottoscrivo la 2), salvo che l'aumento del buffer più che "consigliabile" è praticamente "obbligatorio".

A proposito di questo, io lo renderei configurabile a piacere, a prescindere dall'utilizzo o meno dell'opzione "−−multi−threaded".

Anche la 1) sarebbe simpatica. Però piuttosto che una rate fissa, metterei la possibilità di scegliere. Cioè, qualcosa del tipo:   "ricampiona solo se s/r < XX", con XX configurabile.

Una cosa analoga sarebbe utilissima anche (e soprattutto) per gli stream DSD, così da poter evitare di ri-processare ad es. quelli che sono già DSD128 o superiori.

**Comment by marcoc1712** [comment]
il buffer di soc è già un parametro 'nascosto', ci avevo giocato qualche tempo fa,ma senza nessun risultato, posso esporlo senza grossi problemi insieme all'opzione  −−multi−threaded.

L'altra questione è più rognosa ed impatta in modo significativo sulla struttura di C.3PO. Separo le due richieste e vi chiedo di specificare meglio prima.
