### ISSUE TITLE
Possibile problema con "gain"

### ISSUE THREAD

**Issue by pms967** [marcoc1712/C-3PO#6]
Ciao Marco,

devo verificare meglio, ma c'è un possibile problema con l'uso di gain per la riduzione del volume se si usa contemporaneamente la riduzione fissa e quella automatica (gain -h). In breve, la riduzione fissa unitamente a quella automatica può essere applicata in due modi:

1) con una singola invocazione di "gain", cioè:  "**_gain -h $dB_**"  (soluzione preferibile)

2) con due invocazioni separate di "gain", purché l'eventuale riduzione fissa sia applicata **_prima_** di "gain -h", cioè: "**_gain $dB gain -h_**"

(ho usato "$dB" per indicare il valore numerico della riduzione fissa da applicare)

Quello che invece è da evitare (e non vorrei che sia proprio ciò che accade attualmente) è che ci siano due invocazioni separate laddove "gain -h" **_precede_** "gain $dB" ... perché in tal caso "gain -h" potrebbe annullare l'effetto di "gain $dB".

**Comment by marcoc1712** [comment]
ma perché uno dovrebbe impostare sia la riduzione fissa che quella automatica?

comunque, confermo, attualmente avviene questo:  ..."gain -h gain -3" vedrò di invertirli, ma rimango molto dubbioso.

**Comment by pms967** [comment]
> ma perché uno dovrebbe impostare sia la riduzione fissa che quella automatica?

la riduzione automatica introduce la minima riduzione possibile che l'algoritmo ritiene sufficiente ad evitare il clipping nel processing successivo. Ma in alcuni casi (ad es. SDM) oltre a quella potrebbe essere desiderabile lasciare un ulteriore margine fisso. 

> comunque, confermo, attualmente avviene questo: ..."gain -h gain -3" vedrò di invertirli

sarebbe meglio combinarli, mettendone uno solo: "gain -h -3".

si evita un doppio passaggio che, oltre a sprecare inutilmente risorse, introduce più rumore riducendo la qualità (con la combinazione in un unico comando, sox prima calcola il guadagno necessario ad ottenere il risultato e poi lo applica in un colpo solo).

**Comment by marcoc1712** [comment]
Ho cercato qualche documentazione in merito, ma sia nell'help online e nel PDF di SOX è non è presentato come problema. 

1. gain -3 gain -h, provocherebbe che PRIMA sia applicato il -3 e quindi mantenuto a valle grazie il -h, in pratica sposta lo 0. 

2, gain -h -3 equivale a 1, in più i 3db possono essere 'reclamati' da una successiva opzione -r.

3. gain -h gain -4 , la seconda invocazione è annullata dalla prima (da qui la domanda sul senso della cosa), ma non c'è danno, a meno di non inserire tra le 2 un gain -r, che annulla il -h, ma non è possibile se non appena a monte o appena a valle del rate.

4. SOLO il -r interrompe la catena impostata da una invocazione -h, quindi sdm è compreso (o almeno dovrebbe) salvo diversa indicazioni in qualche effetto extra. 

Se vuoi aggiungere una riduzione aggiuntiva, valida SOLO per SDM, metti negli extra effects dopo rate qualcosa come gain -r -4

Anche se trasformassi le cose come indichi tu, NON funzionerebbe, o meglio, avresti una generale diminuzione del gain di x db  al di sotto della soglia di clipping, AGGIUNTIVA rispetto a quelle successive immesse da  gain -h, ma per aggiungere uno variazione effetiva a SDM/Dithering devi comunque usare gli extra effects, ricordandoti di usare opportune combinazioni di gain -r e -h

Detto questo, credo lo farò comunque (invertendo l'ordine dei controlli) per il semplice fatto che così mantengono un valore semantico più corretto.

**Comment by marcoc1712** [comment]
Fatto, disponbile dalla versione 2.0.13
