### ISSUE TITLE
 SoX multi-thread

### ISSUE THREAD

**Issue by marcoc1712** [marcoc1712/C-3PO#7]
Originariamente richiesta da SimoneFil: Vedi #5

Ciao Marco; ti suggerisco una feature da aggiungere per la prossima release che a mio parere può essere molto utile:

Aggiunta al menu Avanzate -> C-3PO (le impostazioni generale). Una casella con: "Enable SoX multi-thread". Ora come ora con una conversione PCM->DSD128 SoX si "beve" il 50% di un core fisico di uno Xeon X5570; che all'incirca è la potenza di un core di un i5 di penultima generazione o un core di un i3 ultima gen. In questo modo si escludono tutte le cpu che sono multi core con TDP molto basso (molte fanless) come i pentium 4core, gli atom 4core e 8core fanless (stile il c2750) che in multithreading riuscirebbero a convertire ma in single core non ce la fanno.

**Comment by marcoc1712** [comment]
si può fare, con alcune limitazioni in windows,   ##purtroppo.
#5

**Comment by marcoc1712** [comment]
Da SimoneFil #5 

 Sì, è un parametro di lancio di sox; basta che tu aggiunga alla stringa −−multi−threaded; è consigliabile anche aumentare il buffer (di default 8192 [byte]) per una questione di prestazioni con l'opzione --buffer 131072 ->(cifra consigliata nella documentazione nel caso si utilizzi il multi thread)

**Comment by marcoc1712** [comment]
Da pms 967

Sottoscriv, salvo che l'aumento del buffer più che "consigliabile" è praticamente "obbligatorio".

A proposito di questo, io lo renderei configurabile a piacere, a prescindere dall'utilizzo o meno dell'opzione "−−multi−threaded".

**Comment by marcoc1712** [comment]
#5 

il buffer di sox è già un parametro 'nascosto', ci avevo giocato qualche tempo fa,ma senza nessun risultato, posso esporlo senza grossi problemi insieme all'opzione −−multi−threaded.

Prossima release.

**Comment by marcoc1712** [comment]
La versione 14.3.0 (distribuita con LMS) non riconosce l'opzione −−multi−threaded e di conseguenza va in errore... 

Da quale versione è 'sicuro' applicare quella opzione?
Grazie.

**Comment by pms967** [comment]
è stata introdotta prima, ma c'erano dei problemi... quindi direi a partire dalla 14.3.1

**Comment by marcoc1712** [comment]
14 3 1 o 14 4 1


2017-03-31 19:14 GMT+02:00 pms967 <notifications@github.com>:

**Comment by marcoc1712** [comment]
Nella 2.0.13
